log:
  Level: info
  Format: text
  ProjectId: ""

server:
  ListenAddress: :7002

telegram:
  Token:
  Debug: false

inline:
  PageSize: 20


storage-service:
  Uri: "http://localhost:7001"
  RequireGoogleIDToken: false

youtube-service:
  Uri: "http://localhost:7004"
  RequireGoogleIDToken: false

user-account:
  StaticUuid: "00000000-0000-0000-0000-000000000000"

webhook:
  ExternalUrl: ""

temp-storage:
  Endpoint:
  AccessKey:
  SecretKey:
  Bucket: melo-temp
  Secure: false

permissions:
  Create:
    AllowedUserIds: []
  Delete:
    AllowedUserIds: []
  Recompute:
    AllowedUserIds: []
  Search:
    AllowedUserIds: []
