linters:
  enable:
    - misspell
    - dupl
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errorlint
    - goconst
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - errcheck
          - errchkjson
version: "2"
