services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.2
    environment: [
      'ES_JAVA_OPTS=-Xms2g -Xmx2g',
      'bootstrap.memory_lock=true',
      'discovery.type=single-node',
      'xpack.security.enabled=false',
      'xpack.security.enrollment.enabled=false',
      'cluster.routing.allocation.disk.watermark.low=600mb',
      'cluster.routing.allocation.disk.watermark.high=500mb',
      'cluster.routing.allocation.disk.watermark.flood_stage=400mb'
    ]
    ports:
      - 9200:9200
    networks:
      - env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    profiles:
      - env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.2
    environment:
      - XPACK_SECURITY_ENABLED=false
      - XPACK_ENTERPRISESEARCH_ENABLED=false
    ports:
      - 5601:5601
    networks:
      - env
    profiles:
      - env

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: minio123
      MINIO_SECRET_KEY: minio123
    ports:
      - 9000:9000
    command: server /data
    profiles:
      - env

  storage-service:
    image: ghcr.io/weoses/storage-service:latest
    environment:
      METADATA-STORAGE_ELASTIC_USERNAME:
      METADATA-STORAGE_ELASTIC_PASSWORD:
      IMAGE-STORAGE_S3_ENDPOINT: minio
      IMAGE-STORAGE_S3_ACCESSKEY: minio123
      IMAGE-STORAGE_S3_SECRETKEY: minio123
      GOOGLE_APPLICATION_CREDENTIALS: $HOME/.config/gcloud/application_default_credentials.json
    restart: unless-stopped
    ports:
      - "127.0.0.1:7001:7001"
    volumes:
      - "./config/storageservice:/app/config"
      - "./config/credentials:/app/credentials"
    networks:
      - env
    profiles:
      - service

networks:
  env: