FROM golang:1.25.0-alpine AS builder

WORKDIR /app
RUN apk add --update --no-cache bash curl \
    gcc g++ vips vips-dev vips-poppler pkgconf \
    poppler-dev musl-dev libc6-compat

COPY ./common common/

COPY ./gateway-service ./gateway-service

WORKDIR /app/gateway-service
RUN go build -a -installsuffix cgo -o output.bin

FROM alpine:latest

WORKDIR /app
RUN apk add curl
COPY --from=builder /app/gateway-service/output.bin gateway-service
COPY ./scripts/entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

COPY ./gateway-service/config.yaml config/config.yaml
ENV APPLICATION_CONFIGPATH "/app/config"

WORKDIR /app
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["/app/gateway-service"]
