FROM golang:1.26-alpine AS builder

WORKDIR /app
RUN apk add --update --no-cache bash curl gcc g++ pkgconf musl-dev

COPY ./gen gen/
COPY ./common common/
COPY ./ffmpeg-service ./ffmpeg-service

WORKDIR /app/ffmpeg-service
RUN go build -a -installsuffix cgo -o output.bin

FROM alpine:latest

WORKDIR /app
RUN apk add --update --no-cache curl ffmpeg cpulimit
COPY --from=builder /app/ffmpeg-service/output.bin ffmpeg-service

WORKDIR /app/config
ENV APPLICATION_CONFIGPATH "/app/config"

WORKDIR /app
ENTRYPOINT ["/app/ffmpeg-service"]
