FROM golang:1.25.0-alpine AS builder

WORKDIR /app
RUN apk add --update --no-cache bash curl \
    gcc g++ vips vips-dev vips-poppler pkgconf \
    poppler-dev musl-dev libc6-compat

COPY ./gen gen/
COPY ./common common/
COPY ./storage-service ./storage-service

WORKDIR /app/storage-service
RUN go build -a -installsuffix cgo -o output.bin

FROM alpine:latest 

WORKDIR /app
RUN apk add curl vips vips-poppler ffmpeg cpulimit
COPY --from=builder /app/storage-service/output.bin storage-service

WORKDIR /app/config
ENV APPLICATION_CONFIGPATH "/app/config"

WORKDIR /app
ENTRYPOINT [ "/app/storage-service" ]