FROM golang:1.24.10-alpine AS builder

WORKDIR /app
RUN apk add --update --no-cache bash curl \
    gcc g++ vips vips-dev vips-poppler pkgconf \
    poppler-dev musl-dev libc6-compat

COPY ./gen gen/
COPY ./common common/
COPY ./storage-service ./storage-service
COPY ./telegram-service ./telegram-service
COPY ./go.work ./go.work
COPY ./go.work.sum ./go.work.sum

RUN go build -a -installsuffix cgo -o storage-service.bin ./storage-service

FROM alpine:latest 

WORKDIR /app
RUN apk add vips vips-poppler
COPY --from=builder /app/storage-service.bin storage-service

WORKDIR /app/config
ENV APPLICATION_CONFIGPATH "/app/config"

WORKDIR /app
ENTRYPOINT [ "/app/storage-service" ]