
### GET index (img)
GET http://localhost:9200/melo-image-metadata
Accept: application/json
Authorization: basic ZWxhc3RpYzplbGFzdGlj


### Search index (img)
GET http://localhost:9200/melo-image-metadata/_search
Accept: application/json
Authorization: basic ZWxhc3RpYzplbGFzdGlj


### GET index (tags)
GET http://localhost:9200/melo-tags
Accept: application/json
Authorization: basic ZWxhc3RpYzplbGFzdGlj


### Search index (tags)
GET http://localhost:9200/melo-tags/_search
Accept: application/json
Authorization: basic ZWxhc3RpYzplbGFzdGlj


### Search by text query
GRPC localhost:7001/proto.memelo.v1.SearchService/SearchMeme

{
  "account_id": "592c313b-e4b8-409c-908c-ddedb2ff5df4",
  "query": ""
}

### Search all query
GRPC localhost:7001/proto.memelo.v1.SearchService/SearchMeme

{
  "account_id": "f6a3e8a0-c3b8-45af-a2d3-7bbe2879e0e6"
}

### Create
GRPC localhost:7001/proto.memelo.v1.SearchService/CreateMeme

{
  "account_id": "f6a3e8a0-c3b8-45af-a2d3-7bbe2879e0e6",
  "raw_image": ""
}



### Delete
GRPC localhost:7001/proto.memelo.v1.SearchService/DeleteMeme

{
 "account_id": "f6a3e8a0-c3b8-45af-a2d3-7bbe2879e0e6",
  "id": "eaa4389c-5f3c-429c-af6c-2e9095b1ede0"
}



### Export
GRPC localhost:7001/proto.memelo.v1.ExportService/ExportImages

{
  "account_id": "f6a3e8a0-c3b8-45af-a2d3-7bbe2879e0e6"
}


### Create tag
GRPC localhost:7001/proto.memelo.v1.TagsService/CreateTag

{
  "tag": "winter",
  "description": "winter"
}

### recompute
GRPC localhost:7001/proto.memelo.v1.RecomputeService/RecomputeOcrData

{
}

###
GRPC localhost:7001/proto.memelo.v1.SearchService/DeleteAll

{
"account_id": "00000000-0000-0000-0000-000000000000"
}


###
GRPC localhost:7004/proto.memelo.v1.YouTubeService/DownloadVideoSync

{
  "account_id": "00000000-0000-0000-0000-000000000000",
  "youtube_url": "https://www.youtube.com/watch?v=3W40tBACFbI"
}