log:
  Level: info

server:
  ListenAddress: :7001

embeddings:
  Dimensions: 1408
  VideoEmbeddingIntervalSec: 10

search:
  SemanticDuplicateThreshold: 0.955
  SemanticTextSearchThreshold: 0.5
  Fuzziness: "AUTO:4,8"


media-storage:
  Endpoint:
  AccessKey:
  SecretKey:
  Bucket: melo-images
  Secure: false

temp-storage:
  Endpoint:
  AccessKey:
  SecretKey:
  Bucket: melo-temp
  Secure: false

temp-storage-expiry: 24h

metadata-db:
  Elastic:
    Addresses:
    Username:
    Password:
    CloudID:
    ApiKey:
  Index: melo-media-metadata

tag-db:
  Elastic:
    Addresses:
    Username:
    Password:
    CloudID:
    ApiKey:
  Index: melo-tags

media-embedding:
  ApiEndpoint: us-central1-aiplatform.googleapis.com:443
  ApiLocation: us-central1
  ProjectName:
  Model: multimodalembedding@001

audio-stt:
  ApiEndpoint: us-speech.googleapis.com:443
  ApiLocation: us
  ProjectName:
  Recognizer: "_"
  Model: chirp_3
  LanguageCodes:
    - 'en-US'
    - 'ru-RU'

image-converter:
  ThumbSize: 360

image-ocr:
  ApiEndpoint: vision.googleapis.com:443

ffmpeg:
  Binary: ffmpeg
  CpuLimit: 0
  ThreadsLimit: 0