log:
  Level: info

server:
  ListenAddress: :7006

storage-service:
  Uri: "http://localhost:7001"
  RequireGoogleIDToken: false

account:
  Id: "00000000-0000-0000-0000-000000000000"

temp-storage:
  Endpoint:
  AccessKey:
  SecretKey:
  Bucket:
  Secure:

jwt:
  Secret: "change-me-in-production"

frontend:
  BaseUrl:
