s3:
  mediaBucket: melo-prod-media
  tempBucket: melo-prod-temp

elastic:
  metadataIndex: melo-prod-media-metadata
  tagIndex: melo-prod-tag-metadata

ingress:
  webappDomain: "webapp.prod.cluster.memelo.cloud"   # e.g. app.example.com
  webhookDomain: "tg-webhook.prod.cluster.memelo.cloud"  # e.g. hooks.example.com
