syntax = "proto3";


option go_package = "github.com/weoses/memelo/gen/proto/v1";
package proto.memelo.v1;

message ResultData {

}

message TimeCodeResultData {
  int32 start = 1;
  int32 end = 2;
  ResultData data = 3;
}

message ImageDto {
  string url = 1;
  optional int32 image_width = 2;
  optional int32 image_height = 3;
}

message MemeDto {
  string id = 1;
  string ocr_result = 2;
  ImageDto image_thumbnail = 3;
  ImageDto media_original = 4;
  repeated string tags = 5;
  string type = 6;
  string caption = 7;
  string audio_transcript = 8;
  string on_screen_text = 9;
  string audio_track = 10;
//  repeated TimeCodeResultData result_data_by_time = 10;
}
message PipelinePagination {
  string searcher = 1;
  repeated string sorting_after = 2;
}

message DeleteAllRequest {
  string account_id = 1;
}

message DeleteAllResponse {}