syntax = "proto3";
import "proto/v1/common.proto";

option go_package = "github.com/weoses/memelo/gen/proto/v1";
package proto.memelo.v1;

import "google/protobuf/struct.proto";

message RecomputeOptions {
  bool compute_extractor = 3;
  bool compute_embedding = 4;
  bool check_duplicates = 5;
  bool update_storage_items = 6;
  bool include_manual_edited = 7;
}

message RecomputeRequest {
  google.protobuf.Struct query = 1;
  RecomputeOptions options = 2;
}

message RecomputeJob {
  string job_id = 1;
}

message RecomputeError {
  string object_id = 1;
  string error_text = 2;
}

message RecomputeJobStatus {
  enum State {
    STATE_UNSPECIFIED = 0;
    STATE_PENDING = 1;
    STATE_RUNNING = 2;
    STATE_DONE = 3;
    STATE_FAILED = 4;
  }

  string job_id = 1;
  State state = 2;
  int32 processed = 3;
  int32 total = 4;
  repeated RecomputeError errors = 5;
  repeated string processed_ids = 6;
}

message RecomputeOneRequest {
  string media_id = 1;
  string account_id = 2;
  RecomputeOptions options = 3;
}

message RecomputeOneResponse {
  bool success = 1;
}


service RecomputeService {
  rpc StartRecomputeJob(RecomputeRequest) returns (RecomputeJob);
  rpc StartRecomputeJobById(RecomputeOneRequest) returns (RecomputeJob);
  rpc GetRecomputeJobStatus(RecomputeJob) returns (RecomputeJobStatus);

}