syntax = "proto3";
import "proto/v1/common.proto";

option go_package = "github.com/weoses/memelo/gen/proto/v1";
package proto.memelo.v1;

enum CreateMemeStatus {
  // The first value in the enum must be zero and should be a default/unspecified value
  STATUS_UNSPECIFIED = 0;
  STATUS_NEW = 1;
  STATUS_DUPLICATE = 2;
}

message MediaDataDto {
  optional string s3_path = 1;
  optional bytes data = 2;
}

message SearchMemeRequest {
  string account_id = 1;
  string query = 2;
  PipelinePagination after_id = 5;
  int32 page_size = 6;
  optional string type = 7;
}

message SearchMemeResponse {
  repeated MemeDto results = 1;
  PipelinePagination last_id = 3;
}

message CreateMemeRequest {
  string account_id = 1;
  optional MediaDataDto image = 2;
  optional MediaDataDto video = 3;
}

message CreateMemeResponse {
  MemeDto result = 1;
  CreateMemeStatus status = 2;
}

message GetMemeRequest{
  string id = 1;
  string account_id = 2;
}

message GetMemeResponse {
  MemeDto result = 1;
}

message DeleteMemeRequest {
  string account_id = 1;
  string id = 2;
}

message DeleteMemeResponse {
  string id = 1;
}

message UpdateMemeRequest {
  string id = 1;
  optional string on_screen_text = 2;
  optional string audio_transcription = 3;
  optional string caption = 4;
  optional string audio_track = 5;
  optional MediaDataDto original = 6;
  optional MediaDataDto thumbnail = 7;
  string account_id = 8;
}

message UpdateMemeResponse {
  MemeDto result = 1;
}

message GetRandomMemeRequest {
  string account_id = 1;
  optional string type = 2;
}

message GetRandomMemeResponse {
  MemeDto result = 1;
}

service SearchService {
  rpc SearchMeme(SearchMemeRequest) returns (SearchMemeResponse);
  rpc CreateMeme(CreateMemeRequest) returns (CreateMemeResponse);
  rpc GetMeme(GetMemeRequest) returns (GetMemeResponse);
  rpc DeleteMeme(DeleteMemeRequest) returns (DeleteMemeResponse);
  rpc UpdateMeme(UpdateMemeRequest) returns (UpdateMemeResponse);

  rpc DeleteAll(DeleteAllRequest) returns (DeleteAllResponse);

  rpc GetRandomMeme(GetRandomMemeRequest) returns (GetRandomMemeResponse);
}
