log:
  Level: info

server:
  ListenAddress: localhost:7004

temp-storage:
  Endpoint:
  AccessKey:
  SecretKey:
  Bucket: melo-temp
  Secure: false

youtube:
  TempDir: ""
  MaxConcurrentDownloads: 4
  JobTtlSeconds: 3600
  ApiKey: ""
  ApiHost: p.savenow.to
  VideoFormat: "720"
