name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "STORAGE: Build "
        uses: docker/build-push-action@v6
        with:
          push: false
          file: Dockerfile-storage-service
          tags: ghcr.io/weoses/storage-service:latest

      - name: "TELEGRAM: Build "
        uses: docker/build-push-action@v6
        with:
          push: false
          file: Dockerfile-telegram-service
          tags: ghcr.io/weoses/telegram-service:latest