name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "STORAGE: Build and push" 
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile-storage-service
          tags: ghcr.io/weoses/storage-service:dev-${{ github.sha }}

      - name: "TELEGRAM: Build and push" 
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile-telegram-service
          tags: ghcr.io/weoses/telegram-service:dev-${{ github.sha }}


  test-deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    environment: memelo-test
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: tests/e2e/go.mod

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        timeout-minutes: 10
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ELASTIC_CLOUDID,ELASTIC_APIKEY,METADATA_ELASTIC_INDEX,TAG_ELASTIC_INDEX,MINIO_ENDPOINT,MINIO_ACCESS_KEY,MINIO_SECRET_KEY,MINIO_SECURE,EMBEDDING_PROJECTNAME,GOOGLE_CREDS_PATH,REPO_URL,DEPLOY_PATH,RELEASE_VERSION,TELEGRAM_TOKEN,POSTGRES_DB,POSTGRES_PASSWORD,TAG,TELEGRAM_WEBHOOK_EXTERNALURL,FFMPEG_CPULIMIT,MEDIA_STORAGE_BUCKET,TEMP_STORAGE_BUCKET
          script: |
            if [ ! -d "$DEPLOY_PATH/.git" ]; then
              git clone "$REPO_URL" "$DEPLOY_PATH"
            fi
            cd "$DEPLOY_PATH"

            docker compose -p memelo down || true

            LAST_CONTAINER=$(docker ps -q -f "name=memelo")
            for i in $LAST_CONTAINER
            do
              echo "Still lasts container $i, removing"
              docker stop "$i"
              docker rm "$i"
            done            

            git fetch --tags origin
            git checkout "$TAG"

            docker compose pull
            docker compose -p memelo up -d --wait --wait-timeout 300
        env:
          ELASTIC_CLOUDID: ${{ secrets.ELASTIC_CLOUDID }}
          ELASTIC_APIKEY: ${{ secrets.ELASTIC_APIKEY }}
          METADATA_ELASTIC_INDEX: ${{vars.METADATA_ELASTIC_INDEX}}
          TAG_ELASTIC_INDEX: ${{vars.TAG_ELASTIC_INDEX}}

          MINIO_ENDPOINT: ${{ vars.MINIO_ENDPOINT }}
          MINIO_ACCESS_KEY: ${{ vars.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MINIO_SECURE: ${{ vars.MINIO_SECURE }}

          EMBEDDING_PROJECTNAME: ${{ vars.EMBEDDING_PROJECTNAME }}
          GOOGLE_CREDS_PATH: ${{ vars.GOOGLE_CREDS_PATH }}
          TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          POSTGRES_DB: ${{vars.POSTGRES_DB}}
          POSTGRES_USER: ${{vars.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORS}}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
          DEPLOY_PATH: ${{ vars.DEPLOY_REPO_PATH }}
          RELEASE_VERSION: dev-${{ github.sha }}
          TAG:  ${{ github.sha }}
          TELEGRAM_WEBHOOK_EXTERNALURL: ${{vars.TELEGRAM_WEBHOOK_EXTERNALURL}}
          FFMPEG_CPULIMIT: ${{vars.FFMPEG_CPULIMIT}}
          MEDIA_STORAGE_BUCKET: ${{vars.MEDIA_STORAGE_BUCKET}}
          TEMP_STORAGE_BUCKET: ${{vars.TEMP_STORAGE_BUCKET}}

      - name: Tests
        uses: robherley/go-test-action@v0
        with:
          moduleDirectory: tests/e2e
        env:
          STORAGE_SERVICE_URI: ${{ vars.TEST_STORAGE_SERVICE_URI }}
          STORAGE_SERVICE_USERNAME: ${{ vars.TEST_PROXY_USERNAME }}
          STORAGE_SERVICE_PASSWORD: ${{ secrets.TEST_PROXY_PASSWORD}}

  release-tag-images:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retag storage-service image by tag
        uses: Nextdoor/docker-image-retag-action@main
        with:
          image: ghcr.io/weoses/storage-service
          source_tag: dev-${{ github.sha }}
          dest_tag: ${{ github.ref_name }}

      - name: Retag telegram-service image by tag
        uses: Nextdoor/docker-image-retag-action@main
        with:
          image: ghcr.io/weoses/telegram-service
          source_tag: dev-${{ github.sha }}
          dest_tag: ${{ github.ref_name }}

  release-make:
    runs-on: ubuntu-latest
    needs:
      - release-tag-images
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v') && endsWith(github.ref_name, '.00')
    steps:
      - name: "Make release"
        uses: softprops/action-gh-release@v2
        with:
          body: |
            **Docker images:**
            `ghcr.io/weoses/storage-service:${{ github.ref_name }}`
            `ghcr.io/weoses/telegram-service:${{ github.ref_name }}`

            **Deploy workflow:** [link](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          generate_release_notes: true

  release-deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - release-tag-images
      - release-make
    environment: memelo-test
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: tests/e2e/go.mod

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        timeout-minutes: 10
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ELASTIC_CLOUDID,ELASTIC_APIKEY,METADATA_ELASTIC_INDEX,TAG_ELASTIC_INDEX,MINIO_ENDPOINT,MINIO_ACCESS_KEY,MINIO_SECRET_KEY,MINIO_SECURE,EMBEDDING_PROJECTNAME,GOOGLE_CREDS_PATH,REPO_URL,DEPLOY_PATH,RELEASE_VERSION,TELEGRAM_TOKEN,POSTGRES_DB,POSTGRES_PASSWORD,TAG,TELEGRAM_WEBHOOK_EXTERNALURL,FFMPEG_CPULIMIT,MEDIA_STORAGE_BUCKET,TEMP_STORAGE_BUCKET
          script: |
            if [ ! -d "$DEPLOY_PATH/.git" ]; then
              git clone "$REPO_URL" "$DEPLOY_PATH"
            fi
            cd "$DEPLOY_PATH"

            docker compose -p memelo down || true

            LAST_CONTAINER=$(docker ps -q -f "name=memelo")
            for i in $LAST_CONTAINER
            do
              echo "Still lasts container $i, removing"
              docker stop "$i"
              docker rm "$i"
            done            

            git fetch --tags origin
            git checkout "$TAG"

            docker compose pull
            docker compose -p memelo up -d --wait --wait-timeout 300
        env:
          ELASTIC_CLOUDID: ${{ secrets.ELASTIC_CLOUDID }}
          ELASTIC_APIKEY: ${{ secrets.ELASTIC_APIKEY }}
          METADATA_ELASTIC_INDEX: ${{vars.METADATA_ELASTIC_INDEX}}
          TAG_ELASTIC_INDEX: ${{vars.TAG_ELASTIC_INDEX}}

          MINIO_ENDPOINT: ${{ vars.MINIO_ENDPOINT }}
          MINIO_ACCESS_KEY: ${{ vars.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MINIO_SECURE: ${{ vars.MINIO_SECURE }}
          EMBEDDING_PROJECTNAME: ${{ vars.EMBEDDING_PROJECTNAME }}
          GOOGLE_CREDS_PATH: ${{ vars.GOOGLE_CREDS_PATH }}
          TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          POSTGRES_DB: ${{vars.POSTGRES_DB}}
          POSTGRES_USER: ${{vars.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORS}}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
          DEPLOY_PATH: ${{ vars.DEPLOY_REPO_PATH }}
          RELEASE_VERSION: ${{ github.ref_name }}
          TAG:  ${{ github.sha }}
          TELEGRAM_WEBHOOK_EXTERNALURL: ${{vars.TELEGRAM_WEBHOOK_EXTERNALURL}}
          FFMPEG_CPULIMIT: ${{vars.FFMPEG_CPULIMIT}}
          MEDIA_STORAGE_BUCKET: ${{vars.MEDIA_STORAGE_BUCKET}}
          TEMP_STORAGE_BUCKET: ${{vars.TEMP_STORAGE_BUCKET}}

      - name: Tests
        uses: robherley/go-test-action@v0
        with:
          moduleDirectory: tests/e2e
        env:
          STORAGE_SERVICE_URI: ${{ vars.TEST_STORAGE_SERVICE_URI }}
          STORAGE_SERVICE_USERNAME: ${{ vars.TEST_PROXY_USERNAME }}
          STORAGE_SERVICE_PASSWORD: ${{ secrets.TEST_PROXY_PASSWORD}}