name: release-build&deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "STORAGE: Build and push"
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile-storage-service
          tags: |
            ghcr.io/weoses/storage-service:${{ github.ref_name }}

      - name: "TELEGRAM: Build and push"
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile-telegram-service
          tags: |
            ghcr.io/weoses/telegram-service:${{ github.ref_name }}

      - name: "Make release"
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          body: |
            Version: ${{ github.ref_name }}
            Images:
             - ghcr.io/weoses/storage-service:${{ github.ref_name }}
             - ghcr.io/weoses/telegram-service:${{ github.ref_name }}
          generate_release_notes: true
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ELASTIC_USERNAME,ELASTIC_PASSWORD,ELASTIC_JAVA_OPTS,MINIO_ENDPOINT,MINIO_ACCESS_KEY,MINIO_SECRET_KEY,MINIO_SECURE,IMAGE_EMBEDDING_PROJECTNAME,GOOGLE_CREDS_PATH,REPO_URL,TAG,DEPLOY_PATH,RELEASE_VERSION
          script: |
            if [ ! -d "$DEPLOY_PATH/.git" ]; then
              git clone "$REPO_URL" "$DEPLOY_PATH"
            fi
            cd "$DEPLOY_PATH"
            
            docker compose down || true
            
            LAST_CONTAINER=$(docker ps -q -f "memelo")
            for i in $LAST_CONTAINER
            do
              echo "Still lasts container $i, removing"
              docker stop "$i"
              docker rm "$i"
            done            
  
            git fetch --tags origin
            git checkout "$TAG"

            docker compose pull
            docker compose up -p memelo -d --wait --wait-timeout 300
        env:
          ELASTIC_USERNAME: ${{ vars.ELASTIC_USERNAME }}
          ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
          ELASTIC_JAVA_OPTS: ${{ vars.ELASTIC_JAVA_OPTS }}
          MINIO_ENDPOINT: ${{ vars.MINIO_ENDPOINT }}
          MINIO_ACCESS_KEY: ${{ vars.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MINIO_SECURE: ${{ vars.MINIO_SECURE }}
          IMAGE_EMBEDDING_PROJECTNAME: ${{ vars.IMAGE_EMBEDDING_PROJECTNAME }}
          GOOGLE_CREDS_PATH: ${{ vars.GOOGLE_CREDS_PATH }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
          TAG: ${{ github.ref_name }}
          DEPLOY_PATH: ${{ vars.DEPLOY_REPO_PATH }}
          RELEASE_VERSION: ${{ github.ref_name }}