name: deploy-test

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - "**"
jobs:
  wait-for-images:
    runs-on: ubuntu-latest
    steps:
     - name: Wait for storage-service
       uses: PaulLesur/wait-docker-image-github-action@v1.0
       with:
         image: ghcr.io/weoses/storage-service
         tag: dev-${{ github.sha }}
         timeout: 300

     - name: Wait for telegram-service
       uses: PaulLesur/wait-docker-image-github-action@v1.0
       with:
         image: ghcr.io/weoses/telegram-service
         tag: dev-${{ github.sha }}
         timeout: 300

  deploy:
    runs-on: ubuntu-latest
    needs: wait-for-images
    environment: memelo-test
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: tests/e2e/go.mod

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: ELASTIC_USERNAME,ELASTIC_PASSWORD,ELASTIC_JAVA_OPTS,MINIO_ENDPOINT,MINIO_ACCESS_KEY,MINIO_SECRET_KEY,MINIO_SECURE,IMAGE_EMBEDDING_PROJECTNAME,GOOGLE_CREDS_PATH,REPO_URL,TAG,DEPLOY_PATH,RELEASE_VERSION,TELEGRAM_TOKEN,POSTGRES_DB,POSTGRES_PASSWORD
          script: |
            if [ ! -d "$DEPLOY_PATH/.git" ]; then
              git clone "$REPO_URL" "$DEPLOY_PATH"
            fi
            cd "$DEPLOY_PATH"
            
            docker compose -p memelo down || true
            
            LAST_CONTAINER=$(docker ps -q -f "name=memelo")
            for i in $LAST_CONTAINER
            do
              echo "Still lasts container $i, removing"
              docker stop "$i"
              docker rm "$i"
            done            
            
            git fetch --tags origin
            git checkout "$TAG"
  
            docker compose pull
            docker compose -p memelo up -d --wait --wait-timeout 300
        env:
          ELASTIC_USERNAME: ${{ vars.ELASTIC_USERNAME }}
          ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
          ELASTIC_JAVA_OPTS: ${{ vars.ELASTIC_JAVA_OPTS }}
          MINIO_ENDPOINT: ${{ vars.MINIO_ENDPOINT }}
          MINIO_ACCESS_KEY: ${{ vars.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MINIO_SECURE: ${{ vars.MINIO_SECURE }}
          IMAGE_EMBEDDING_PROJECTNAME: ${{ vars.IMAGE_EMBEDDING_PROJECTNAME }}
          GOOGLE_CREDS_PATH: ${{ vars.GOOGLE_CREDS_PATH }}
          TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          POSTGRES_DB: ${{vars.POSTGRES_DB}}
          POSTGRES_USER: ${{vars.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORS}}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
          TAG: dev-${{ github.sha }}
          DEPLOY_PATH: ${{ vars.DEPLOY_REPO_PATH }}
          RELEASE_VERSION: ${{ github.ref_name }}

      - name: Tests
        uses: robherley/go-test-action@v0
        with:
          moduleDirectory: tests/e2e
        env:
          STORAGE_SERVICE_URI: ${{ vars.TEST_STORAGE_SERVICE_URI }}
          STORAGE_SERVICE_USERNAME: ${{ vars.TEST_PROXY_USERNAME }}
          STORAGE_SERVICE_PASSWORD: ${{ secrets.TEST_PROXY_PASSWORD}}