name: lint

on: [push, pull_request]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [common, storage-service, telegram-service]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.module }}/go.mod
          cache: false

      - uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ${{ matrix.module }}
          version: latest
